version: '3.9'

services:

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=intelligent_lms
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h 127.0.0.1 -p 5432 -U superuser -d intelligent_lms" ]
      interval: 5s
      timeout: 5s
      retries: 5


  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8011:8011"
    environment:
      - DATABASE_URL=postgresql+asyncpg://superuser:postgres@db:5432/intelligent_lms
    depends_on:
      db:
         condition: service_healthy
    command: [ "poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8011", "--reload" ]
    volumes:
      - .:/project

volumes:
  postgres_data:
